// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/rpc/proto/auth/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenRequest struct {
	// token
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a551c8d06eb20ad, []int{0}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenResponse struct {
	// 状态码 200-正常 2-未创建文化云 0-错误 401-未授权 405-无权限
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 用户类型 文化云-culture 用户-user 运营后台-admin
	UserType string `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	// 用户类型对应的用户ID
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 文化云ID
	CloudId string `protobuf:"bytes,4,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// 用户主ID
	Bid                  string   `protobuf:"bytes,5,opt,name=bid,proto3" json:"bid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a551c8d06eb20ad, []int{1}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TokenResponse) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *TokenResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenResponse) GetCloudId() string {
	if m != nil {
		return m.CloudId
	}
	return ""
}

func (m *TokenResponse) GetBid() string {
	if m != nil {
		return m.Bid
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenRequest)(nil), "auth.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "auth.TokenResponse")
}

func init() { proto.RegisterFile("server/rpc/proto/auth/auth.proto", fileDescriptor_6a551c8d06eb20ad) }

var fileDescriptor_6a551c8d06eb20ad = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbd, 0x4a, 0xc5, 0x40,
	0x10, 0x85, 0x89, 0xd9, 0xfb, 0x37, 0x78, 0x41, 0x46, 0xc1, 0x55, 0x9b, 0x4b, 0xb0, 0xb0, 0x4a,
	0x40, 0x11, 0x6c, 0x2d, 0xd3, 0x58, 0x84, 0x60, 0x2b, 0x49, 0x76, 0x20, 0xc1, 0x90, 0x5d, 0xf7,
	0x47, 0xc9, 0x0b, 0xf8, 0xdc, 0xb2, 0x63, 0x0a, 0x2d, 0x6f, 0xb3, 0x9c, 0xef, 0x9c, 0x39, 0x30,
	0xb3, 0x70, 0x70, 0x64, 0x3f, 0xc9, 0x16, 0xd6, 0x74, 0x85, 0xb1, 0xda, 0xeb, 0xa2, 0x09, 0xbe,
	0xe7, 0x27, 0x67, 0x46, 0x11, 0x75, 0x76, 0x0b, 0xa7, 0xb5, 0x7e, 0xa7, 0xa9, 0xa2, 0x8f, 0x40,
	0xce, 0xe3, 0x05, 0xac, 0x7c, 0x64, 0x99, 0x1c, 0x92, 0xbb, 0x5d, 0xf5, 0x0b, 0xd9, 0x77, 0x02,
	0xfb, 0x65, 0xcc, 0x19, 0x3d, 0x39, 0x42, 0x04, 0xd1, 0x69, 0x45, 0x3c, 0x96, 0x56, 0xac, 0xf1,
	0x06, 0x76, 0xc1, 0x91, 0x7d, 0xf3, 0xb3, 0x21, 0x79, 0xc2, 0xfd, 0x6d, 0x34, 0xea, 0xd9, 0x10,
	0x5e, 0xc2, 0x86, 0xc3, 0x41, 0xc9, 0x94, 0xa3, 0x75, 0xc4, 0x52, 0xe1, 0x15, 0x6c, 0xbb, 0x51,
	0x07, 0x15, 0x13, 0xc1, 0xc9, 0x86, 0xb9, 0x54, 0x78, 0x06, 0x69, 0x3b, 0x28, 0xb9, 0x62, 0x37,
	0xca, 0xfb, 0x2f, 0x10, 0xcf, 0xc1, 0xf7, 0xf8, 0x08, 0xf0, 0xda, 0x8c, 0x83, 0xe2, 0xa5, 0x10,
	0x73, 0xbe, 0xeb, 0xef, 0x21, 0xd7, 0xe7, 0xff, 0xbc, 0x65, 0xeb, 0x27, 0xd8, 0x73, 0xed, 0x45,
	0xfb, 0xe3, 0x9a, 0xed, 0x9a, 0x3f, 0xed, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x43, 0x8a, 0x7a,
	0x20, 0x58, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// ValidToken 验证token
	ValidToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// ValidNotToken 验证通用token
	ValidNotToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) ValidToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/ValidToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ValidNotToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/ValidNotToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// ValidToken 验证token
	ValidToken(context.Context, *TokenRequest) (*TokenResponse, error)
	// ValidNotToken 验证通用token
	ValidNotToken(context.Context, *TokenRequest) (*TokenResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_ValidToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ValidToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/ValidToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ValidToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ValidNotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ValidNotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/ValidNotToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ValidNotToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidToken",
			Handler:    _Auth_ValidToken_Handler,
		},
		{
			MethodName: "ValidNotToken",
			Handler:    _Auth_ValidNotToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/rpc/proto/auth/auth.proto",
}
